POST http://localhost:8080/api/send-message
Content-Type: application/json

{
    "name":"Yua Mikami",
    "email": "jav@gmail.com",
    "password":"123456"
}

###

GET http://localhost:8081
Content-Type: application/json
###
